define([
    './shortcuts',
    './folders',
    './applications',
    './control-panel',
    './data-sources',
    './devices',
    './drives',
    './environment-variables',
    './files',
    './folder-options',
    './ini-files',
    './internet-settings',
    './local-users-and-groups',
    './network-options',
    './network-shares',
    './power-options',
    './printers',
    './regional-options',
    './registry',
    './scheduled-tasks',
    './services',
    './start-menu'
], function(shortcuts, folders, applications, controlPanel, dataSources, devices, drives,
        environmentVariables, files, folderOptions, iniFiles, internetSettings,
        localUsersAndGroups, networkOptions, networkShares, powerOptions, printers,
        regionalOptions, registry, scheduledTasks, services, startMenu) {
    "use strict";

    return {
        shortcuts: shortcuts,
        folders: folders,
        applications: applications,
        control_panel: controlPanel,
        data_sources: dataSources,
        devices: devices,
        drives: drives,
        environment_variables: environmentVariables,
        files: files,
        folder_options: folderOptions,
        ini_files: iniFiles,
        internet_settings: internetSettings,
        local_users_and_groups: localUsersAndGroups,
        network_options: networkOptions,
        network_shares: networkShares,
        power_options: powerOptions,
        printers: printers,
        regional_options: regionalOptions,
        registry: registry,
        scheduled_tasks: scheduledTasks,
        services: services,
        start_menu: startMenu
    };
});
